# Generated by Django 5.2.4 on 2025-07-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_backdrop_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='backdrop',
            field=models.ImageField(blank=True, default='fallback2.png', upload_to=''),
        ),
    ]
