# Generated by Django 5.2.4 on 2025-07-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_backdrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_path', models.ImageField(blank=True, default='default_cast.png', upload_to='cast_profiles/')),
                ('original_name', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='posts.post')),
            ],
        ),
    ]
