# Generated by Django 5.2.4 on 2025-07-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_overview_post_popularity_post_rating_castmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('profile_path', models.ImageField(blank=True, upload_to='casts/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='posts.post')),
            ],
        ),
        migrations.DeleteModel(
            name='CastMember',
        ),
    ]
