# Generated by Django 5.2.4 on 2025-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_popularity_remove_post_rating_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
