# Generated by Django 5.2.4 on 2025-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_popularity_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='profile_path',
            field=models.ImageField(blank=True, default='fallback3.png', upload_to='casts/'),
        ),
    ]
